version: '3'
services:
  tui:
    image: "nate/tui-when-im-done"
  qdrant:
    image: "qdrant/qdrant:latest"
    ports: 
      - "6334:6334"
    environment:
      QDRANT__SERVICE__GRPC_PORT: "6334"
    volumes: 
      - "./data/qdrant:/qdrant/storage"


