[project]
name = "konteksto-builder"
version = "0.1.0"
description = "some scripts for building out the qdrant db"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "fastembed>=0.6.1",
]
